networks:
  frontend: # Name of the network
    external: true # Set to true to use an existing network

services:
  npm:
    image: 'jc21/nginx-proxy-manager'
    container_name: npm # Optional - Name of the container
    restart: always
   # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - /root/s-npm/data:/data  # Change host path to your liking
      - /root/s-npm/letsencrypt:/etc/letsencrypt # Change host path to your liking
      - ports:
          - '80:80' # Public HTTP Port
          - '443:443' # Public HTTPS Port
          - '81:81' # Admin Web Port